<a href="https://colab.research.google.com/github/Rishsing73/rishsing73.github.io/blob/master/Deeplabcut_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
data = pd.read_csv("/content/drive/MyDrive/Trial_2-Shruti_Priya-2021-03-16/videos/result.csv")

In [4]:
data.head()

      scorer  ... DLC_resnet_50_Trial_2Mar16shuffle1_50500.8
0  bodyparts  ...                                       Tail
1     coords  ...                                 likelihood
2          0  ...                     1.3768672943115234e-05
3          1  ...                      1.531839370727539e-05
4          2  ...                     1.6629695892333984e-05

[5 rows x 10 columns]

In [ ]:
data.columns.values

array(['scorer', 'DLC_resnet_50_Trial_2Mar16shuffle1_50500',
       'DLC_resnet_50_Trial_2Mar16shuffle1_50500.1',
       'DLC_resnet_50_Trial_2Mar16shuffle1_50500.2',
       'DLC_resnet_50_Trial_2Mar16shuffle1_50500.3',
       'DLC_resnet_50_Trial_2Mar16shuffle1_50500.4',
       'DLC_resnet_50_Trial_2Mar16shuffle1_50500.5',
       'DLC_resnet_50_Trial_2Mar16shuffle1_50500.6',
       'DLC_resnet_50_Trial_2Mar16shuffle1_50500.7',
       'DLC_resnet_50_Trial_2Mar16shuffle1_50500.8'], dtype=object)

In [21]:
data = data.drop(labels=[0,1], axis=0)
data.head()

  scorer  ... DLC_resnet_50_Trial_2Mar16shuffle1_50500.8
2      0  ...                     1.3768672943115234e-05
3      1  ...                      1.531839370727539e-05
4      2  ...                     1.6629695892333984e-05
5      3  ...                      1.570582389831543e-05
6      4  ...                     1.5974044799804688e-05

[5 rows x 10 columns]

In [73]:
data1 = data[["DLC_resnet_50_Trial_2Mar16shuffle1_50500","DLC_resnet_50_Trial_2Mar16shuffle1_50500.1"]]
data1 = data1.astype(np.float32)
data1.head()

   DLC_resnet_50_Trial_2Mar16shuffle1_50500  DLC_resnet_50_Trial_2Mar16shuffle1_50500.1
2                                535.223694                                  521.039368
3                                535.849487                                  519.568726
4                                535.390137                                  521.420044
5                                535.883362                                  519.993042
6                                535.784912                                  520.443848

In [72]:
def window(dat,x_st,x_en,y_st,y_en):
  total_frames = len(dat)
  filter = dat["DLC_resnet_50_Trial_2Mar16shuffle1_50500"] > x_st
  filter2 = dat["DLC_resnet_50_Trial_2Mar16shuffle1_50500"] < x_en
  filter3 = dat["DLC_resnet_50_Trial_2Mar16shuffle1_50500.1"] > y_st
  filter4 = dat["DLC_resnet_50_Trial_2Mar16shuffle1_50500.1"] < y_en
  dat.where(filter & filter2 & filter3 & filter4, inplace = True)
  dat = dat.dropna()
  final_frames = len(dat)
  return(final_frames/25)

In [5]:
# x1 = data["DLC_resnet_50_Trial_2Mar16shuffle1_50500"]
# x1 = x1[2:] 
# x1 = x1.to_numpy(dtype ='float32')
# y1 = data["DLC_resnet_50_Trial_2Mar16shuffle1_50500.1"]
# y1 = y1[2:]
# y1 = y1.to_numpy(dtype ='float32')
# type(x1)

numpy.ndarray

In [6]:
# type(x1[1])

numpy.float32

In [18]:
# k = np.where(x1<300); x1 = x1[k[0]]
# k = np.where(x1>200); x1 = x1[k[0]]
# k = np.where(y1<600); y1 = y1[k[0]]  
# k = np.where(y1>400); y1 = y1[k[0]]
# len((y1))

4073

In [ ]:
# k = np.where(x1<300,x1>280)

ValueError: ignored

In [ ]:
# x1[k]

array([  7.7168417 ,   7.71807766,   7.85549736, ..., 269.39108276,
       213.17289734,   7.80298042])

In [ ]:
# x1 = x1.astype(np.float)

In [19]:
# data.head()

      scorer  ... DLC_resnet_50_Trial_2Mar16shuffle1_50500.8
0  bodyparts  ...                                       Tail
1     coords  ...                                 likelihood
2          0  ...                     1.3768672943115234e-05
3          1  ...                      1.531839370727539e-05
4          2  ...                     1.6629695892333984e-05

[5 rows x 10 columns]

In [78]:
k = window(data1,100,1000,100,1000)
print(k)

344.52

In [76]:
filter = data1["DLC_resnet_50_Trial_2Mar16shuffle1_50500"] > 100
filter2 = data1["DLC_resnet_50_Trial_2Mar16shuffle1_50500"] <1000
filter3 = data1["DLC_resnet_50_Trial_2Mar16shuffle1_50500.1"] < 1000
filter4 = data1["DLC_resnet_50_Trial_2Mar16shuffle1_50500.1"] > 100
data1.where(filter & filter2 & filter3 & filter4, inplace = True)

In [77]:
data1.describe

<bound method NDFrame.describe of        DLC_resnet_50_Trial_2Mar16shuffle1_50500  DLC_resnet_50_Trial_2Mar16shuffle1_50500.1
2                                    535.223694                                  521.039368
3                                    535.849487                                  519.568726
4                                    535.390137                                  521.420044
5                                    535.883362                                  519.993042
6                                    535.784912                                  520.443848
...                                         ...                                         ...
15861                                       NaN                                         NaN
15862                                       NaN                                         NaN
15863                                       NaN                                         NaN
15864                                       NaN                                         NaN
15865                                       NaN                                         NaN

[15864 rows x 2 columns]>

In [71]:
len(data1)

8613

In [70]:
data1 = data1.dropna()